---
abstract: 'the spawn of MooX-Struct and Sub-Talisman'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Sub::Talisman::Struct
name: Sub-Talisman-Struct
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  MooX::Struct: 0.006
  Sub::Talisman: 0
  perl: 5.12.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Sub-Talisman-Struct
  homepage: https://metacpan.org/release/Sub-Talisman-Struct
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-sub-talisman-struct
version: 0.004
